obj-$(CONFIG_BROADCOM_V4L2_HCI_LDISC) += line_discipline_driver/
obj-$(CONFIG_BROADCOM_V4L2_FM_DRV) += v4l2_fm_driver/
obj-$(CONFIG_BROADCOM_V4L2_ANT_DRV) += v4l2_ant_driver/
obj-$(CONFIG_BROADCOM_V4L2_BT_DRV) += bt_protocol_driver/
